version: '3.8'

services:
  vitejs-app:
    container_name: vitejs-app
    image: dakeinu/curriculum:latest
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - webnet

networks:
  webnet: